version: "3.9"
services:
  frontend:
    build: Frontend
    ports:
      - "8080:8080"
  server:
    build: Server
    ports:
      - "8081:8081"
    environment:
      - DB_LOCATION=/usr/local/smartmeal/database.db
    volumes:
      - "/usr/local/smartmeal/:/usr/local/smartmeal/"
